logging:
  level:
    root: info
    studio.echo: trace
    org.springframework.boot.context.properties: DEBUG
    org.springframework.boot.context.properties.bind: DEBUG
spring:
  application:
    name: studio-api
  ### JPA Config ###
  jpa:
    # database-platform: org.hibernate.dialect.MySQLInnoDBDialect, org.hibernate.dialect.MySQL8Dialect
    # database-platform: org.hibernate.dialect.PostgreSQLDialect, org.hibernate.dialect.PostgreSQL10Dialect
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    properties: 
      hibernate: 
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  ### DATASOURCE Config ###
  datasource:
    primary:
      url: jdbc:log4jdbc:postgresql://localhost:5432/peis
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: peis
      password: peis
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5               # 최소 유휴 커넥션 수
        maximum-pool-size: 5         # 커넥션 풀 최대 크기 (일반 웹서비스 기준)
        idle-timeout: 600000          # 커넥션 유휴 종료 시간 (10분, 단위: ms)
        max-lifetime: 1800000         # 커넥션 최대 수명 (30분, 단위: ms)
        connection-timeout: 30000     # 커넥션 획득 timeout (30초)
        pool-name: PrimaryHikariCP     # 풀 이름 지정
        auto-commit: false             # 자동 커밋 여부 
studio:
  banner-mode: off
  env:  
    log:
      enabled: true
      print-values: true 
  persistence:
      jpa: true
  i18n:
    resources:
      - classpath:/i18n/messages
    encoding: UTF-8
    cache-seconds: 60      
  features:
    application-properties:
      enabled: true
  security:
    default-roles:
      - ROLE_USER
    password-encoder: bcrypt # bcrypt, sha256, pbkdf2
    jwt: 
      secret: rPdiCjP07o9Soenln4t58AZr5bgaTLpXllDbbRs6yZ0=
      access-token-expiry: 3600000 # 1 hour
      refresh-token-expiry: 3600000 # 1 hour
      issuer: www.greentogether.go.kr     
    cors:
      allowed-origins:
        - "http://localhost:3000"
        - "https://myfrontend.com"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
      allowed-headers:
        - Authorization
        - Content-Type
      exposed-headers:
        - Authorization
      allow-credentials: true
      max-age: 3600
    permit:
      permit-all:
        - /
        - /index.html
        - /api/auth/**
      role:
        USER:
          - /api/profile/**

