-- =================================================
-- PACKAGE: ATTACHMENT SERVICE
-- CREATE : 2025.11.20
-- UPDATE :
-- =================================================


CREATE TABLE TB_APPLICATION_ATTACHMENT (
    ATTACHMENT_ID BIGSERIAL PRIMARY KEY, -- 첨부파일 ID
    OBJECT_TYPE INTEGER, -- 객체 타입
    OBJECT_ID BIGINT, -- 객체 ID
    CONTENT_TYPE VARCHAR(255), -- 콘텐츠 타입
    FILE_NAME VARCHAR(255), -- 파일 이름
    FILE_SIZE BIGINT, -- 파일 크기
    CREATED_BY BIGINT NOT NULL, -- 사용자 ID
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(), -- 생성일
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW() -- 수정일
);

COMMENT ON TABLE TB_APPLICATION_ATTACHMENT IS '첨부파일 테이블';

CREATE TABLE TB_APPLICATION_ATTACHMENT_DATA (
    ATTACHMENT_ID BIGINT NOT NULL, -- 첨부파일 ID
    ATTACHMENT_DATA OID, -- 첨부파일 데이터
    PRIMARY KEY (ATTACHMENT_ID)
);

COMMENT ON TABLE TB_APPLICATION_ATTACHMENT_DATA IS '첨부파일 데이터 테이블';

CREATE TABLE TB_APPLICATION_ATTACHMENT_PROPERTY (
    ATTACHMENT_ID BIGINT NOT NULL, -- 첨부파일 ID
    PROPERTY_NAME VARCHAR(100), -- 프로퍼티 이름
    PROPERTY_VALUE VARCHAR(1024), -- 프로퍼티 값
    PRIMARY KEY (ATTACHMENT_ID, PROPERTY_NAME)
);

COMMENT ON TABLE TB_APPLICATION_ATTACHMENT_PROPERTY IS '첨부파일 프로퍼티 테이블';
CREATE INDEX IDX_TB_APPLICATION_ATTACHMENT_OBJECT ON TB_APPLICATION_ATTACHMENT (OBJECT_TYPE, OBJECT_ID);
CREATE INDEX IDX_TB_APPLICATION_ATTACHMENT_CREATED_BY ON TB_APPLICATION_ATTACHMENT (CREATED_BY);
