SET @add_link_type_sql = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG ADD COLUMN LINK_TYPE VARCHAR(40) NOT NULL DEFAULT ''OBJECT_STORAGE_PRESIGNED'' AFTER TTL_SECONDS',
        'SELECT 1')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG'
      AND COLUMN_NAME = 'LINK_TYPE'
);
PREPARE add_link_type_stmt FROM @add_link_type_sql;
EXECUTE add_link_type_stmt;
DEALLOCATE PREPARE add_link_type_stmt;

SET @add_token_hash_sql = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG ADD COLUMN TOKEN_HASH VARCHAR(64) NULL AFTER LINK_TYPE',
        'SELECT 1')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG'
      AND COLUMN_NAME = 'TOKEN_HASH'
);
PREPARE add_token_hash_stmt FROM @add_token_hash_sql;
EXECUTE add_token_hash_stmt;
DEALLOCATE PREPARE add_token_hash_stmt;

ALTER TABLE TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG
    MODIFY STORAGE_PROVIDER_ID VARCHAR(100) NULL,
    MODIFY BUCKET VARCHAR(255) NULL,
    MODIFY OBJECT_KEY_HASH VARCHAR(64) NULL;
