-- =================================================
-- PACKAGE: ATTACHMENT SERVICE
-- CREATE ATTACHMENT SIGNED DOWNLOAD AUDIT LOG
-- =================================================

CREATE TABLE TB_APPLICATION_ATTACHMENT_DOWNLOAD_LOG (
    DOWNLOAD_LOG_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ISSUE_LOG_ID BIGINT NULL,
    TOKEN_HASH VARCHAR(64) NULL,
    ATTACHMENT_ID BIGINT NULL,
    OBJECT_TYPE INTEGER NULL,
    OBJECT_ID BIGINT NULL,
    LINK_TYPE VARCHAR(40) NOT NULL,
    REQUESTED_AT DATETIME(6) NOT NULL,
    RESULT VARCHAR(40) NOT NULL,
    HTTP_STATUS INTEGER NOT NULL,
    DOWNLOADED_BYTES BIGINT NULL,
    CLIENT_IP VARCHAR(45) NULL,
    USER_AGENT VARCHAR(512) NULL,
    ERROR_CODE VARCHAR(80) NULL,
    INDEX IDX_TB_ATTACHMENT_DOWNLOAD_ISSUE (ISSUE_LOG_ID),
    INDEX IDX_TB_ATTACHMENT_DOWNLOAD_TOKEN (TOKEN_HASH),
    INDEX IDX_TB_ATTACHMENT_DOWNLOAD_ATTACHMENT (ATTACHMENT_ID),
    INDEX IDX_TB_ATTACHMENT_DOWNLOAD_OBJECT (OBJECT_TYPE, OBJECT_ID),
    INDEX IDX_TB_ATTACHMENT_DOWNLOAD_REQUESTED_AT (REQUESTED_AT),
    INDEX IDX_TB_ATTACHMENT_DOWNLOAD_RESULT (RESULT),
    INDEX IDX_TB_ATTACHMENT_DOWNLOAD_CLIENT_IP (CLIENT_IP)
);
