package studio.one.platform.markdown.application;

import studio.one.platform.markdown.domain.MarkdownPipelineStage;

public record MarkdownResumeOptions(
        MarkdownPipelineStage fromStage,
        Boolean runChunking,
        Boolean runRagIndex,
        Boolean runSkillExtraction,
        String chunkingStrategy,
        Integer chunkMaxSize,
        Integer chunkOverlap,
        String chunkUnit,
        String blockifyLlmProvider,
        String blockifyLlmModel,
        Boolean blockifyPiiMaskingEnabled,
        String embeddingProfileId,
        String embeddingProvider,
        String embeddingModel,
        Integer embeddingDimension,
        Boolean useLlmKeywordExtraction,
        String skillExtractionMode,
        Boolean generateSkillEmbeddings,
        String skillEmbeddingProvider,
        String skillEmbeddingModel,
        Integer skillEmbeddingDimension,
        Boolean ocrRequired,
        String ocrLanguage,
        String ocrMode,
        Boolean mathVisionCorrection,
        String embeddingDeploymentId) {

    public MarkdownResumeOptions(
            MarkdownPipelineStage fromStage,
            Boolean runChunking,
            Boolean runRagIndex,
            Boolean runSkillExtraction,
            String chunkingStrategy,
            Integer chunkMaxSize,
            Integer chunkOverlap,
            String chunkUnit,
            String blockifyLlmProvider,
            String blockifyLlmModel,
            Boolean blockifyPiiMaskingEnabled,
            String embeddingProfileId,
            String embeddingProvider,
            String embeddingModel,
            Integer embeddingDimension,
            Boolean useLlmKeywordExtraction,
            String skillExtractionMode,
            Boolean generateSkillEmbeddings,
            String skillEmbeddingProvider,
            String skillEmbeddingModel,
            Integer skillEmbeddingDimension,
            Boolean ocrRequired,
            String ocrLanguage,
            String ocrMode,
            Boolean mathVisionCorrection) {
        this(fromStage, runChunking, runRagIndex, runSkillExtraction,
                chunkingStrategy, chunkMaxSize, chunkOverlap, chunkUnit,
                blockifyLlmProvider, blockifyLlmModel, blockifyPiiMaskingEnabled,
                embeddingProfileId, embeddingProvider, embeddingModel, embeddingDimension,
                useLlmKeywordExtraction, skillExtractionMode, generateSkillEmbeddings,
                skillEmbeddingProvider, skillEmbeddingModel, skillEmbeddingDimension,
                ocrRequired, ocrLanguage, ocrMode, mathVisionCorrection, null);
    }

    public MarkdownResumeOptions(
            MarkdownPipelineStage fromStage,
            Boolean runChunking,
            Boolean runRagIndex,
            Boolean runSkillExtraction,
            String chunkingStrategy,
            Integer chunkMaxSize,
            Integer chunkOverlap,
            String chunkUnit,
            String blockifyLlmProvider,
            String blockifyLlmModel,
            Boolean blockifyPiiMaskingEnabled,
            String embeddingProfileId,
            String embeddingProvider,
            String embeddingModel,
            Integer embeddingDimension,
            Boolean useLlmKeywordExtraction,
            String skillExtractionMode,
            Boolean generateSkillEmbeddings,
            String skillEmbeddingProvider,
            String skillEmbeddingModel,
            Integer skillEmbeddingDimension,
            Boolean ocrRequired) {
        this(fromStage, runChunking, runRagIndex, runSkillExtraction,
                chunkingStrategy, chunkMaxSize, chunkOverlap, chunkUnit,
                blockifyLlmProvider, blockifyLlmModel, blockifyPiiMaskingEnabled,
                embeddingProfileId, embeddingProvider, embeddingModel, embeddingDimension,
                useLlmKeywordExtraction, skillExtractionMode, generateSkillEmbeddings,
                skillEmbeddingProvider, skillEmbeddingModel, skillEmbeddingDimension, ocrRequired, null, null, null, null);
    }

    public MarkdownResumeOptions(
            MarkdownPipelineStage fromStage,
            Boolean runChunking,
            Boolean runRagIndex,
            Boolean runSkillExtraction,
            String chunkingStrategy,
            Integer chunkMaxSize,
            Integer chunkOverlap,
            String chunkUnit,
            String blockifyLlmProvider,
            String blockifyLlmModel,
            Boolean blockifyPiiMaskingEnabled,
            String embeddingProfileId,
            String embeddingProvider,
            String embeddingModel,
            Integer embeddingDimension,
            Boolean useLlmKeywordExtraction,
            String skillExtractionMode,
            Boolean generateSkillEmbeddings,
            String skillEmbeddingProvider,
            String skillEmbeddingModel,
            Integer skillEmbeddingDimension,
            Boolean ocrRequired,
            String ocrLanguage) {
        this(fromStage, runChunking, runRagIndex, runSkillExtraction,
                chunkingStrategy, chunkMaxSize, chunkOverlap, chunkUnit,
                blockifyLlmProvider, blockifyLlmModel, blockifyPiiMaskingEnabled,
                embeddingProfileId, embeddingProvider, embeddingModel, embeddingDimension,
                useLlmKeywordExtraction, skillExtractionMode, generateSkillEmbeddings,
                skillEmbeddingProvider, skillEmbeddingModel, skillEmbeddingDimension, ocrRequired, ocrLanguage, null, null, null);
    }

    public MarkdownResumeOptions(
            MarkdownPipelineStage fromStage,
            Boolean runChunking,
            Boolean runRagIndex,
            Boolean runSkillExtraction,
            String chunkingStrategy,
            Integer chunkMaxSize,
            Integer chunkOverlap,
            String chunkUnit,
            String blockifyLlmProvider,
            String blockifyLlmModel,
            Boolean blockifyPiiMaskingEnabled,
            String embeddingProfileId,
            String embeddingProvider,
            String embeddingModel,
            Integer embeddingDimension,
            Boolean useLlmKeywordExtraction,
            String skillExtractionMode,
            Boolean generateSkillEmbeddings,
            String skillEmbeddingProvider,
            String skillEmbeddingModel,
            Integer skillEmbeddingDimension,
            Boolean ocrRequired,
            String ocrLanguage,
            String ocrMode) {
        this(fromStage, runChunking, runRagIndex, runSkillExtraction,
                chunkingStrategy, chunkMaxSize, chunkOverlap, chunkUnit,
                blockifyLlmProvider, blockifyLlmModel, blockifyPiiMaskingEnabled,
                embeddingProfileId, embeddingProvider, embeddingModel, embeddingDimension,
                useLlmKeywordExtraction, skillExtractionMode, generateSkillEmbeddings,
                skillEmbeddingProvider, skillEmbeddingModel, skillEmbeddingDimension, ocrRequired, ocrLanguage, ocrMode, null, null);
    }

    public MarkdownResumeOptions(
            MarkdownPipelineStage fromStage,
            Boolean runChunking,
            Boolean runRagIndex,
            Boolean runSkillExtraction,
            String chunkingStrategy,
            Integer chunkMaxSize,
            Integer chunkOverlap,
            String chunkUnit,
            String blockifyLlmProvider,
            String blockifyLlmModel,
            Boolean blockifyPiiMaskingEnabled,
            String embeddingProfileId,
            String embeddingProvider,
            String embeddingModel,
            Integer embeddingDimension,
            Boolean useLlmKeywordExtraction,
            String skillExtractionMode,
            Boolean generateSkillEmbeddings,
            String skillEmbeddingProvider,
            String skillEmbeddingModel,
            Integer skillEmbeddingDimension) {
        this(fromStage, runChunking, runRagIndex, runSkillExtraction,
                chunkingStrategy, chunkMaxSize, chunkOverlap, chunkUnit,
                blockifyLlmProvider, blockifyLlmModel, blockifyPiiMaskingEnabled,
                embeddingProfileId, embeddingProvider, embeddingModel, embeddingDimension,
                useLlmKeywordExtraction, skillExtractionMode, generateSkillEmbeddings,
                skillEmbeddingProvider, skillEmbeddingModel, skillEmbeddingDimension, null, null, null, null, null);
    }

    public MarkdownResumeOptions(
            MarkdownPipelineStage fromStage,
            Boolean runChunking,
            Boolean runRagIndex,
            Boolean runSkillExtraction,
            String chunkingStrategy,
            Integer chunkMaxSize,
            Integer chunkOverlap,
            String chunkUnit,
            String embeddingProfileId,
            String embeddingProvider,
            String embeddingModel,
            Integer embeddingDimension,
            Boolean useLlmKeywordExtraction,
            Boolean generateSkillEmbeddings,
            String skillEmbeddingProvider,
            String skillEmbeddingModel,
            Integer skillEmbeddingDimension) {
        this(fromStage, runChunking, runRagIndex, runSkillExtraction,
                chunkingStrategy, chunkMaxSize, chunkOverlap, chunkUnit,
                null, null, null,
                embeddingProfileId, embeddingProvider, embeddingModel, embeddingDimension,
                useLlmKeywordExtraction, null, generateSkillEmbeddings,
                skillEmbeddingProvider, skillEmbeddingModel, skillEmbeddingDimension, null, null, null, null, null);
    }

    public MarkdownResumeOptions(
            MarkdownPipelineStage fromStage,
            Boolean runChunking,
            Boolean runRagIndex,
            Boolean runSkillExtraction,
            String chunkingStrategy,
            Integer chunkMaxSize,
            Integer chunkOverlap,
            String chunkUnit,
            String embeddingProfileId,
            String embeddingProvider,
            String embeddingModel,
            Integer embeddingDimension,
            Boolean useLlmKeywordExtraction,
            String skillExtractionMode,
            Boolean generateSkillEmbeddings,
            String skillEmbeddingProvider,
            String skillEmbeddingModel,
            Integer skillEmbeddingDimension) {
        this(fromStage, runChunking, runRagIndex, runSkillExtraction,
                chunkingStrategy, chunkMaxSize, chunkOverlap, chunkUnit,
                null, null, null,
                embeddingProfileId, embeddingProvider, embeddingModel, embeddingDimension,
                useLlmKeywordExtraction, skillExtractionMode, generateSkillEmbeddings,
                skillEmbeddingProvider, skillEmbeddingModel, skillEmbeddingDimension, null, null, null, null, null);
    }

    public static MarkdownResumeOptions fromStage(MarkdownPipelineStage stage) {
        return new MarkdownResumeOptions(
                stage,
                null, null, null,
                null, null, null, null, null, null,
                null, null, null, null,
                null, null, null, null, null, null, null, null, null, null, null, null);
    }
}
