-- =================================================
-- PACKAGE: ATTACHMENT SERVICE
-- CREATE ATTACHMENT DOWNLOAD URL ISSUE AUDIT LOG
-- =================================================

CREATE TABLE TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG (
    LOG_ID BIGSERIAL PRIMARY KEY,
    ATTACHMENT_ID BIGINT NOT NULL,
    OBJECT_TYPE INTEGER NOT NULL,
    OBJECT_ID BIGINT NOT NULL,
    ENDPOINT_KIND VARCHAR(20) NOT NULL,
    ISSUED_BY_USER_ID BIGINT,
    ISSUED_BY_PRINCIPAL_NAME VARCHAR(255),
    ISSUED_AT TIMESTAMPTZ NOT NULL,
    EXPIRES_AT TIMESTAMPTZ NOT NULL,
    TTL_SECONDS BIGINT NOT NULL,
    LINK_TYPE VARCHAR(40) NOT NULL,
    TOKEN_HASH VARCHAR(64),
    STORAGE_PROVIDER_ID VARCHAR(100),
    BUCKET VARCHAR(255),
    OBJECT_KEY_HASH VARCHAR(64),
    CLIENT_IP VARCHAR(45),
    USER_AGENT VARCHAR(512)
);

COMMENT ON TABLE TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG IS '첨부파일 다운로드 URL 발급 감사 로그';
CREATE INDEX IDX_TB_ATTACHMENT_URL_ISSUE_ATTACHMENT ON TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG (ATTACHMENT_ID);
CREATE INDEX IDX_TB_ATTACHMENT_URL_ISSUE_OBJECT ON TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG (OBJECT_TYPE, OBJECT_ID);
CREATE INDEX IDX_TB_ATTACHMENT_URL_ISSUE_ISSUED_AT ON TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG (ISSUED_AT);
