ALTER TABLE TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG
    ADD COLUMN IF NOT EXISTS LINK_TYPE VARCHAR(40) NOT NULL DEFAULT 'OBJECT_STORAGE_PRESIGNED';

ALTER TABLE TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG
    ADD COLUMN IF NOT EXISTS TOKEN_HASH VARCHAR(64);

ALTER TABLE TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG
    ALTER COLUMN STORAGE_PROVIDER_ID DROP NOT NULL,
    ALTER COLUMN BUCKET DROP NOT NULL,
    ALTER COLUMN OBJECT_KEY_HASH DROP NOT NULL,
    ALTER COLUMN OBJECT_KEY_HASH TYPE VARCHAR(64);
