-- =================================================
-- PACKAGE: ATTACHMENT SERVICE
-- CREATE ATTACHMENT SIGNED DOWNLOAD AUDIT LOG
-- =================================================

CREATE TABLE TB_APPLICATION_ATTACHMENT_DOWNLOAD_LOG (
    DOWNLOAD_LOG_ID BIGSERIAL PRIMARY KEY,
    ISSUE_LOG_ID BIGINT,
    TOKEN_HASH VARCHAR(64),
    ATTACHMENT_ID BIGINT,
    OBJECT_TYPE INTEGER,
    OBJECT_ID BIGINT,
    LINK_TYPE VARCHAR(40) NOT NULL,
    REQUESTED_AT TIMESTAMPTZ NOT NULL,
    RESULT VARCHAR(40) NOT NULL,
    HTTP_STATUS INTEGER NOT NULL,
    DOWNLOADED_BYTES BIGINT,
    CLIENT_IP VARCHAR(45),
    USER_AGENT VARCHAR(512),
    ERROR_CODE VARCHAR(80)
);

COMMENT ON TABLE TB_APPLICATION_ATTACHMENT_DOWNLOAD_LOG IS '첨부파일 application signed download 접근 감사 로그';
CREATE INDEX IDX_TB_ATTACHMENT_DOWNLOAD_ISSUE ON TB_APPLICATION_ATTACHMENT_DOWNLOAD_LOG (ISSUE_LOG_ID);
CREATE INDEX IDX_TB_ATTACHMENT_DOWNLOAD_TOKEN ON TB_APPLICATION_ATTACHMENT_DOWNLOAD_LOG (TOKEN_HASH);
CREATE INDEX IDX_TB_ATTACHMENT_DOWNLOAD_ATTACHMENT ON TB_APPLICATION_ATTACHMENT_DOWNLOAD_LOG (ATTACHMENT_ID);
CREATE INDEX IDX_TB_ATTACHMENT_DOWNLOAD_OBJECT ON TB_APPLICATION_ATTACHMENT_DOWNLOAD_LOG (OBJECT_TYPE, OBJECT_ID);
CREATE INDEX IDX_TB_ATTACHMENT_DOWNLOAD_REQUESTED_AT ON TB_APPLICATION_ATTACHMENT_DOWNLOAD_LOG (REQUESTED_AT);
CREATE INDEX IDX_TB_ATTACHMENT_DOWNLOAD_RESULT ON TB_APPLICATION_ATTACHMENT_DOWNLOAD_LOG (RESULT);
CREATE INDEX IDX_TB_ATTACHMENT_DOWNLOAD_CLIENT_IP ON TB_APPLICATION_ATTACHMENT_DOWNLOAD_LOG (CLIENT_IP);
