ALTER TABLE TB_PLATFORM_WORKSPACE
    DROP INDEX UK_PLATFORM_WORKSPACE_PATH,
    DROP INDEX UK_PLATFORM_WORKSPACE_PARENT_SLUG,
    MODIFY COMPANY_ID BIGINT NOT NULL,
    ADD COLUMN PARENT_KEY BIGINT GENERATED ALWAYS AS (COALESCE(PARENT_ID, 0)) STORED,
    ADD UNIQUE KEY UK_PLATFORM_WORKSPACE_COMPANY_PATH (COMPANY_ID, PATH),
    ADD UNIQUE KEY UK_PLATFORM_WORKSPACE_COMPANY_PARENT_SLUG (COMPANY_ID, PARENT_KEY, SLUG);
