CREATE TEMPORARY TABLE TMP_WORKSPACE_COMPANY_SCOPE_GUARD (
    FAIL_IF_PRESENT BIGINT PRIMARY KEY
);

INSERT INTO TMP_WORKSPACE_COMPANY_SCOPE_GUARD (FAIL_IF_PRESENT) VALUES (1);

INSERT INTO TMP_WORKSPACE_COMPANY_SCOPE_GUARD (FAIL_IF_PRESENT)
SELECT 1
FROM TB_PLATFORM_WORKSPACE CHILD
JOIN TB_PLATFORM_WORKSPACE PARENT ON PARENT.WORKSPACE_ID = CHILD.PARENT_ID
WHERE NOT (CHILD.COMPANY_ID <=> PARENT.COMPANY_ID)
LIMIT 1;

INSERT INTO TMP_WORKSPACE_COMPANY_SCOPE_GUARD (FAIL_IF_PRESENT)
SELECT 1
FROM TB_PLATFORM_WORKSPACE WORKSPACE
JOIN TB_PLATFORM_WORKSPACE ROOT ON ROOT.WORKSPACE_ID = WORKSPACE.ROOT_ID
WHERE NOT (WORKSPACE.COMPANY_ID <=> ROOT.COMPANY_ID)
LIMIT 1;

DROP TEMPORARY TABLE TMP_WORKSPACE_COMPANY_SCOPE_GUARD;

ALTER TABLE TB_PLATFORM_WORKSPACE
    DROP INDEX UK_PLATFORM_WORKSPACE_PATH,
    DROP INDEX UK_PLATFORM_WORKSPACE_PARENT_SLUG,
    MODIFY COMPANY_ID BIGINT NOT NULL,
    ADD COLUMN PARENT_KEY BIGINT GENERATED ALWAYS AS (COALESCE(PARENT_ID, 0)) STORED,
    ADD UNIQUE KEY UK_PLATFORM_WORKSPACE_COMPANY_PATH (COMPANY_ID, PATH),
    ADD UNIQUE KEY UK_PLATFORM_WORKSPACE_COMPANY_PARENT_SLUG (COMPANY_ID, PARENT_KEY, SLUG);
