CREATE TABLE IF NOT EXISTS TB_PLATFORM_WORKSPACE (
    WORKSPACE_ID BIGINT NOT NULL AUTO_INCREMENT,
    PARENT_ID BIGINT NULL,
    ROOT_ID BIGINT NULL,
    NAME VARCHAR(255) NOT NULL,
    SLUG VARCHAR(100) NOT NULL,
    PATH VARCHAR(1024) NOT NULL,
    DEPTH INT NOT NULL DEFAULT 0,
    POSITION INT NOT NULL DEFAULT 0,
    VISIBILITY VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    ARCHIVED BOOLEAN NOT NULL DEFAULT FALSE,
    ARCHIVED_AT TIMESTAMP NULL,
    ARCHIVED_BY BIGINT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (WORKSPACE_ID),
    UNIQUE KEY UK_PLATFORM_WORKSPACE_PATH (PATH),
    UNIQUE KEY UK_PLATFORM_WORKSPACE_PARENT_SLUG (PARENT_ID, SLUG),
    KEY IDX_PLATFORM_WORKSPACE_PARENT (PARENT_ID),
    KEY IDX_PLATFORM_WORKSPACE_ROOT (ROOT_ID),
    CONSTRAINT FK_PLATFORM_WORKSPACE_PARENT FOREIGN KEY (PARENT_ID) REFERENCES TB_PLATFORM_WORKSPACE(WORKSPACE_ID),
    CONSTRAINT FK_PLATFORM_WORKSPACE_ROOT FOREIGN KEY (ROOT_ID) REFERENCES TB_PLATFORM_WORKSPACE(WORKSPACE_ID)
);

CREATE TABLE IF NOT EXISTS TB_PLATFORM_WORKSPACE_CLOSURE (
    ANCESTOR_ID BIGINT NOT NULL,
    DESCENDANT_ID BIGINT NOT NULL,
    DEPTH INT NOT NULL,
    PRIMARY KEY (ANCESTOR_ID, DESCENDANT_ID),
    KEY IDX_PLATFORM_WORKSPACE_CLOSURE_DESC (DESCENDANT_ID),
    CONSTRAINT FK_PLATFORM_WORKSPACE_CLOSURE_ANCESTOR FOREIGN KEY (ANCESTOR_ID) REFERENCES TB_PLATFORM_WORKSPACE(WORKSPACE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PLATFORM_WORKSPACE_CLOSURE_DESCENDANT FOREIGN KEY (DESCENDANT_ID) REFERENCES TB_PLATFORM_WORKSPACE(WORKSPACE_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TB_PLATFORM_WORKSPACE_MEMBER (
    MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT,
    WORKSPACE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MEMBER_ID),
    UNIQUE KEY UK_PLATFORM_WORKSPACE_MEMBER (WORKSPACE_ID, USER_ID),
    KEY IDX_PLATFORM_WORKSPACE_MEMBER_USER (USER_ID),
    CONSTRAINT FK_PLATFORM_WORKSPACE_MEMBER_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES TB_PLATFORM_WORKSPACE(WORKSPACE_ID) ON DELETE CASCADE
);
