ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD COLUMN TEAM_ID BIGINT NULL;

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD COLUMN ACCESS_MODE VARCHAR(20) NOT NULL DEFAULT 'INHERIT';

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD COLUMN TEAM_ROOT_KEY BIGINT GENERATED ALWAYS AS (
        CASE WHEN PARENT_ID IS NULL THEN TEAM_ID ELSE NULL END
    ) STORED;

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD COLUMN LEGACY_COMPANY_KEY BIGINT GENERATED ALWAYS AS (
        CASE WHEN TEAM_ID IS NULL THEN COMPANY_ID ELSE NULL END
    ) STORED;

ALTER TABLE TB_PLATFORM_WORKSPACE
    MODIFY COMPANY_ID BIGINT NULL;

ALTER TABLE TB_PLATFORM_WORKSPACE
    DROP INDEX UK_PLATFORM_WORKSPACE_COMPANY_PATH;

ALTER TABLE TB_PLATFORM_WORKSPACE
    DROP INDEX UK_PLATFORM_WORKSPACE_COMPANY_PARENT_SLUG;

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD CONSTRAINT CK_PLATFORM_WORKSPACE_OWNER_SCOPE
        CHECK (TEAM_ID IS NOT NULL OR COMPANY_ID IS NOT NULL);

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD CONSTRAINT CK_PLATFORM_WORKSPACE_ACCESS_MODE
        CHECK (ACCESS_MODE IN ('INHERIT', 'RESTRICTED'));

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD CONSTRAINT FK_PLATFORM_WORKSPACE_TEAM
        FOREIGN KEY (TEAM_ID) REFERENCES TB_PLATFORM_TEAM(TEAM_ID);

CREATE INDEX IDX_PLATFORM_WORKSPACE_TEAM
    ON TB_PLATFORM_WORKSPACE (TEAM_ID);

CREATE UNIQUE INDEX UK_PLATFORM_WORKSPACE_COMPANY_PATH
    ON TB_PLATFORM_WORKSPACE (LEGACY_COMPANY_KEY, PATH_HASH);

CREATE UNIQUE INDEX UK_PLATFORM_WORKSPACE_COMPANY_PARENT_SLUG
    ON TB_PLATFORM_WORKSPACE (LEGACY_COMPANY_KEY, PARENT_KEY, SLUG);

CREATE UNIQUE INDEX UK_PLATFORM_WORKSPACE_TEAM_PATH
    ON TB_PLATFORM_WORKSPACE (TEAM_ID, PATH_HASH);

CREATE UNIQUE INDEX UK_PLATFORM_WORKSPACE_TEAM_PARENT_SLUG
    ON TB_PLATFORM_WORKSPACE (TEAM_ID, PARENT_KEY, SLUG);

CREATE UNIQUE INDEX UK_PLATFORM_WORKSPACE_TEAM_ROOT
    ON TB_PLATFORM_WORKSPACE (TEAM_ROOT_KEY);
