CREATE TABLE IF NOT EXISTS TB_PLATFORM_WORKSPACE (
    WORKSPACE_ID BIGSERIAL PRIMARY KEY,
    PARENT_ID BIGINT,
    ROOT_ID BIGINT,
    NAME VARCHAR(255) NOT NULL,
    SLUG VARCHAR(100) NOT NULL,
    PATH VARCHAR(1024) NOT NULL,
    DEPTH INTEGER NOT NULL DEFAULT 0,
    POSITION INTEGER NOT NULL DEFAULT 0,
    VISIBILITY VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    ARCHIVED BOOLEAN NOT NULL DEFAULT FALSE,
    ARCHIVED_AT TIMESTAMPTZ,
    ARCHIVED_BY BIGINT,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UK_PLATFORM_WORKSPACE_PATH UNIQUE (PATH),
    CONSTRAINT UK_PLATFORM_WORKSPACE_PARENT_SLUG UNIQUE (PARENT_ID, SLUG),
    CONSTRAINT FK_PLATFORM_WORKSPACE_PARENT FOREIGN KEY (PARENT_ID) REFERENCES TB_PLATFORM_WORKSPACE(WORKSPACE_ID),
    CONSTRAINT FK_PLATFORM_WORKSPACE_ROOT FOREIGN KEY (ROOT_ID) REFERENCES TB_PLATFORM_WORKSPACE(WORKSPACE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_PLATFORM_WORKSPACE_ROOT_SLUG
    ON TB_PLATFORM_WORKSPACE (SLUG)
    WHERE PARENT_ID IS NULL;
CREATE INDEX IF NOT EXISTS IDX_PLATFORM_WORKSPACE_PARENT ON TB_PLATFORM_WORKSPACE (PARENT_ID);
CREATE INDEX IF NOT EXISTS IDX_PLATFORM_WORKSPACE_ROOT ON TB_PLATFORM_WORKSPACE (ROOT_ID);

CREATE TABLE IF NOT EXISTS TB_PLATFORM_WORKSPACE_CLOSURE (
    ANCESTOR_ID BIGINT NOT NULL,
    DESCENDANT_ID BIGINT NOT NULL,
    DEPTH INTEGER NOT NULL,
    PRIMARY KEY (ANCESTOR_ID, DESCENDANT_ID),
    CONSTRAINT FK_PLATFORM_WORKSPACE_CLOSURE_ANCESTOR FOREIGN KEY (ANCESTOR_ID) REFERENCES TB_PLATFORM_WORKSPACE(WORKSPACE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PLATFORM_WORKSPACE_CLOSURE_DESCENDANT FOREIGN KEY (DESCENDANT_ID) REFERENCES TB_PLATFORM_WORKSPACE(WORKSPACE_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_PLATFORM_WORKSPACE_CLOSURE_DESC ON TB_PLATFORM_WORKSPACE_CLOSURE (DESCENDANT_ID);

CREATE TABLE IF NOT EXISTS TB_PLATFORM_WORKSPACE_MEMBER (
    MEMBER_ID BIGSERIAL PRIMARY KEY,
    WORKSPACE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UK_PLATFORM_WORKSPACE_MEMBER UNIQUE (WORKSPACE_ID, USER_ID),
    CONSTRAINT FK_PLATFORM_WORKSPACE_MEMBER_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES TB_PLATFORM_WORKSPACE(WORKSPACE_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_PLATFORM_WORKSPACE_MEMBER_USER ON TB_PLATFORM_WORKSPACE_MEMBER (USER_ID);
