CREATE TEMPORARY TABLE TMP_WORKSPACE_COMPANY_SCOPE_GUARD (
    FAIL_IF_PRESENT BIGINT PRIMARY KEY
);

INSERT INTO TMP_WORKSPACE_COMPANY_SCOPE_GUARD (FAIL_IF_PRESENT) VALUES (1);

INSERT INTO TMP_WORKSPACE_COMPANY_SCOPE_GUARD (FAIL_IF_PRESENT)
SELECT 1
FROM TB_PLATFORM_WORKSPACE CHILD
JOIN TB_PLATFORM_WORKSPACE PARENT ON PARENT.WORKSPACE_ID = CHILD.PARENT_ID
WHERE CHILD.COMPANY_ID IS DISTINCT FROM PARENT.COMPANY_ID
LIMIT 1;

INSERT INTO TMP_WORKSPACE_COMPANY_SCOPE_GUARD (FAIL_IF_PRESENT)
SELECT 1
FROM TB_PLATFORM_WORKSPACE WORKSPACE
JOIN TB_PLATFORM_WORKSPACE ROOT ON ROOT.WORKSPACE_ID = WORKSPACE.ROOT_ID
WHERE WORKSPACE.COMPANY_ID IS DISTINCT FROM ROOT.COMPANY_ID
LIMIT 1;

DROP TABLE TMP_WORKSPACE_COMPANY_SCOPE_GUARD;

ALTER TABLE TB_PLATFORM_WORKSPACE
    ALTER COLUMN COMPANY_ID SET NOT NULL;

ALTER TABLE TB_PLATFORM_WORKSPACE
    DROP CONSTRAINT IF EXISTS UK_PLATFORM_WORKSPACE_PATH;

ALTER TABLE TB_PLATFORM_WORKSPACE
    DROP CONSTRAINT IF EXISTS UK_PLATFORM_WORKSPACE_PARENT_SLUG;

DROP INDEX IF EXISTS UK_PLATFORM_WORKSPACE_ROOT_SLUG;

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD CONSTRAINT UK_PLATFORM_WORKSPACE_COMPANY_PATH UNIQUE (COMPANY_ID, PATH);

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD CONSTRAINT UK_PLATFORM_WORKSPACE_COMPANY_PARENT_SLUG UNIQUE (COMPANY_ID, PARENT_ID, SLUG);

CREATE UNIQUE INDEX IF NOT EXISTS UK_PLATFORM_WORKSPACE_COMPANY_ROOT_SLUG
    ON TB_PLATFORM_WORKSPACE (COMPANY_ID, SLUG)
    WHERE PARENT_ID IS NULL;
