ALTER TABLE TB_PLATFORM_WORKSPACE
    ALTER COLUMN COMPANY_ID SET NOT NULL;

ALTER TABLE TB_PLATFORM_WORKSPACE
    DROP CONSTRAINT IF EXISTS UK_PLATFORM_WORKSPACE_PATH;

ALTER TABLE TB_PLATFORM_WORKSPACE
    DROP CONSTRAINT IF EXISTS UK_PLATFORM_WORKSPACE_PARENT_SLUG;

DROP INDEX IF EXISTS UK_PLATFORM_WORKSPACE_ROOT_SLUG;

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD CONSTRAINT UK_PLATFORM_WORKSPACE_COMPANY_PATH UNIQUE (COMPANY_ID, PATH);

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD CONSTRAINT UK_PLATFORM_WORKSPACE_COMPANY_PARENT_SLUG UNIQUE (COMPANY_ID, PARENT_ID, SLUG);

CREATE UNIQUE INDEX IF NOT EXISTS UK_PLATFORM_WORKSPACE_COMPANY_ROOT_SLUG
    ON TB_PLATFORM_WORKSPACE (COMPANY_ID, SLUG)
    WHERE PARENT_ID IS NULL;
