ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD COLUMN TEAM_ID BIGINT;

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD COLUMN ACCESS_MODE VARCHAR(20) NOT NULL DEFAULT 'INHERIT';

ALTER TABLE TB_PLATFORM_WORKSPACE
    ALTER COLUMN COMPANY_ID DROP NOT NULL;

ALTER TABLE TB_PLATFORM_WORKSPACE
    DROP CONSTRAINT UK_PLATFORM_WORKSPACE_COMPANY_PATH;

ALTER TABLE TB_PLATFORM_WORKSPACE
    DROP CONSTRAINT UK_PLATFORM_WORKSPACE_COMPANY_PARENT_SLUG;

DROP INDEX UK_PLATFORM_WORKSPACE_COMPANY_ROOT_SLUG;

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD CONSTRAINT CK_PLATFORM_WORKSPACE_OWNER_SCOPE
        CHECK (TEAM_ID IS NOT NULL OR COMPANY_ID IS NOT NULL);

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD CONSTRAINT CK_PLATFORM_WORKSPACE_ACCESS_MODE
        CHECK (ACCESS_MODE IN ('INHERIT', 'RESTRICTED'));

ALTER TABLE TB_PLATFORM_WORKSPACE
    ADD CONSTRAINT FK_PLATFORM_WORKSPACE_TEAM
        FOREIGN KEY (TEAM_ID) REFERENCES TB_PLATFORM_TEAM(TEAM_ID);

CREATE INDEX IDX_PLATFORM_WORKSPACE_TEAM
    ON TB_PLATFORM_WORKSPACE (TEAM_ID);

CREATE UNIQUE INDEX UK_PLATFORM_WORKSPACE_COMPANY_PATH
    ON TB_PLATFORM_WORKSPACE (COMPANY_ID, PATH)
    WHERE TEAM_ID IS NULL;

CREATE UNIQUE INDEX UK_PLATFORM_WORKSPACE_COMPANY_PARENT_SLUG
    ON TB_PLATFORM_WORKSPACE (COMPANY_ID, PARENT_ID, SLUG)
    WHERE TEAM_ID IS NULL AND PARENT_ID IS NOT NULL;

CREATE UNIQUE INDEX UK_PLATFORM_WORKSPACE_COMPANY_ROOT_SLUG
    ON TB_PLATFORM_WORKSPACE (COMPANY_ID, SLUG)
    WHERE TEAM_ID IS NULL AND PARENT_ID IS NULL;

CREATE UNIQUE INDEX UK_PLATFORM_WORKSPACE_TEAM_PATH
    ON TB_PLATFORM_WORKSPACE (TEAM_ID, PATH)
    WHERE TEAM_ID IS NOT NULL;

CREATE UNIQUE INDEX UK_PLATFORM_WORKSPACE_TEAM_PARENT_SLUG
    ON TB_PLATFORM_WORKSPACE (TEAM_ID, PARENT_ID, SLUG)
    WHERE TEAM_ID IS NOT NULL AND PARENT_ID IS NOT NULL;

CREATE UNIQUE INDEX UK_PLATFORM_WORKSPACE_TEAM_ROOT
    ON TB_PLATFORM_WORKSPACE (TEAM_ID)
    WHERE TEAM_ID IS NOT NULL AND PARENT_ID IS NULL;
