-- =================================================
-- PACKAGE: ATTACHMENT SERVICE
-- CREATE ATTACHMENT DOWNLOAD URL ISSUE AUDIT LOG
-- =================================================

CREATE TABLE TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG (
    LOG_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ATTACHMENT_ID BIGINT NOT NULL,
    OBJECT_TYPE INTEGER NOT NULL,
    OBJECT_ID BIGINT NOT NULL,
    ENDPOINT_KIND VARCHAR(20) NOT NULL,
    ISSUED_BY_USER_ID BIGINT NULL,
    ISSUED_BY_PRINCIPAL_NAME VARCHAR(255) NULL,
    ISSUED_AT DATETIME(6) NOT NULL,
    EXPIRES_AT DATETIME(6) NOT NULL,
    TTL_SECONDS BIGINT NOT NULL,
    LINK_TYPE VARCHAR(40) NOT NULL,
    TOKEN_HASH VARCHAR(64) NULL,
    STORAGE_PROVIDER_ID VARCHAR(100) NULL,
    BUCKET VARCHAR(255) NULL,
    OBJECT_KEY_HASH VARCHAR(64) NULL,
    CLIENT_IP VARCHAR(45) NULL,
    USER_AGENT VARCHAR(512) NULL,
    INDEX IDX_TB_ATTACHMENT_URL_ISSUE_ATTACHMENT (ATTACHMENT_ID),
    INDEX IDX_TB_ATTACHMENT_URL_ISSUE_OBJECT (OBJECT_TYPE, OBJECT_ID),
    INDEX IDX_TB_ATTACHMENT_URL_ISSUE_ISSUED_AT (ISSUED_AT)
);
