ALTER TABLE TB_APPLICATION_ATTACHMENT_URL_ISSUE_LOG
    ADD COLUMN IF NOT EXISTS LINK_TYPE VARCHAR(40) NOT NULL DEFAULT 'OBJECT_STORAGE_PRESIGNED' AFTER TTL_SECONDS,
    ADD COLUMN IF NOT EXISTS TOKEN_HASH VARCHAR(64) NULL AFTER LINK_TYPE,
    MODIFY STORAGE_PROVIDER_ID VARCHAR(100) NULL,
    MODIFY BUCKET VARCHAR(255) NULL,
    MODIFY OBJECT_KEY_HASH VARCHAR(64) NULL;
