-- Canonicalize identifiers only when the persisted vector was generated by the
-- same official model and dimension. The embedding values remain unchanged.
UPDATE tb_ai_document_chunk
SET metadata = COALESCE(metadata, '{}'::jsonb) || jsonb_build_object(
    'embeddingProfileId', 'google-ai/gemini-embedding-001@768',
    'embeddingModelId', 'google-ai/gemini-embedding-001@768',
    'embeddingSpaceId', 'google-ai/gemini-embedding-001@768',
    'embeddingProvider', 'google-ai',
    'embeddingModel', 'gemini-embedding-001',
    'embeddingDimension', 768
)
WHERE embedding_dimension = 768
  AND metadata ->> 'embeddingModel' = 'gemini-embedding-001'
  AND COALESCE(metadata ->> 'embeddingProfileId', 'gemini-768') = 'gemini-768';

UPDATE tb_ai_document_chunk
SET metadata = COALESCE(metadata, '{}'::jsonb) || jsonb_build_object(
    'embeddingProfileId', 'google-ai/gemini-embedding-2@768',
    'embeddingModelId', 'google-ai/gemini-embedding-2@768',
    'embeddingSpaceId', 'google-ai/gemini-embedding-2@768',
    'embeddingProvider', 'google-ai',
    'embeddingModel', 'gemini-embedding-2',
    'embeddingDimension', 768
)
WHERE embedding_dimension = 768
  AND metadata ->> 'embeddingModel' = 'gemini-embedding-2'
  AND COALESCE(metadata ->> 'embeddingProfileId', 'gemini-embedding-2-768') = 'gemini-embedding-2-768';

UPDATE tb_ai_rag_retrieval_evaluation
SET embedding_profile_id = 'google-ai/gemini-embedding-001@768',
    embedding_provider = 'google-ai'
WHERE embedding_model = 'gemini-embedding-001'
  AND embedding_profile_id = 'gemini-768';

UPDATE tb_ai_rag_retrieval_evaluation
SET embedding_profile_id = 'google-ai/gemini-embedding-2@768',
    embedding_provider = 'google-ai'
WHERE embedding_model = 'gemini-embedding-2'
  AND embedding_profile_id = 'gemini-embedding-2-768';
