-- =================================================
-- PACKAGE: SECURITY
-- CREATE : 2024.9.12
-- UPDATE :
-- =================================================

-- Avatar Image Table
CREATE TABLE TB_APPLICATION_AVATAR_IMAGE (
    AVATAR_IMAGE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- ID
    USER_ID BIGINT NOT NULL, -- 사용자 ID
    PRIMARY_IMAGE BOOLEAN DEFAULT TRUE, -- 주 이미지 여부
    FILE_NAME VARCHAR(255) NOT NULL, -- 파일이름
    FILE_SIZE BIGINT NOT NULL, -- 파일크기
    CONTENT_TYPE VARCHAR(50) NOT NULL, -- CONTENT TYPE
    CREATION_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), -- 생성일
    MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) -- 수정일
);

CREATE INDEX TB_APPLICATION_AVATAR_IMAGE_IDX1 ON TB_APPLICATION_AVATAR_IMAGE (USER_ID);

-- Avatar Image Data Table
CREATE TABLE TB_APPLICATION_AVATAR_IMAGE_DATA (
    AVATAR_IMAGE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- ID
    AVATAR_IMAGE_DATA LONGBLOB -- 이미지 데이터 (PostgreSQL에서 LONGBLOB은 LONGBLOB로 변환)
);
