-- =================================================
-- PACKAGE: SECURITY
-- CREATE : 2024.9.12
-- UPDATE :
-- =================================================

-- Avatar Image Table
CREATE TABLE TB_APPLICATION_AVATAR_IMAGE (
    AVATAR_IMAGE_ID BIGSERIAL PRIMARY KEY, -- ID
    USER_ID BIGINT NOT NULL, -- 사용자 ID
    PRIMARY_IMAGE BOOLEAN DEFAULT TRUE, -- 주 이미지 여부
    FILE_NAME VARCHAR(255) NOT NULL, -- 파일이름
    FILE_SIZE BIGINT NOT NULL, -- 파일크기
    CONTENT_TYPE VARCHAR(50) NOT NULL, -- CONTENT TYPE
    CREATION_DATE TIMESTAMPTZ DEFAULT NOW(), -- 생성일
    MODIFIED_DATE TIMESTAMPTZ DEFAULT NOW() -- 수정일
);

CREATE INDEX TB_APPLICATION_AVATAR_IMAGE_IDX1 ON TB_APPLICATION_AVATAR_IMAGE (USER_ID);

COMMENT ON TABLE TB_APPLICATION_AVATAR_IMAGE IS '아바타 이미지 테이블';

-- Avatar Image Data Table
CREATE TABLE TB_APPLICATION_AVATAR_IMAGE_DATA (
    AVATAR_IMAGE_ID BIGSERIAL PRIMARY KEY, -- ID
    AVATAR_IMAGE_DATA BYTEA -- 이미지 데이터 (PostgreSQL에서 LONGBLOB은 BYTEA로 변환)
);

COMMENT ON TABLE TB_APPLICATION_AVATAR_IMAGE_DATA IS '아바타 이미지 데이터 테이블';
