/**
 *
 *      Copyright 2025
 *
 *      Licensed under the Apache License, Version 2.0 (the 'License');
 *      you may not use this file except in compliance with the License.
 *      You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *      Unless required by applicable law or agreed to in writing, software
 *      distributed under the License is distributed on an 'AS IS' BASIS,
 *      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *      See the License for the specific language governing permissions and
 *      limitations under the License.
 *
 *      @file ProblemDetails.java
 *      @date 2025
 *
 */


package studio.one.platform.web.dto;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Locale;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;

import lombok.Builder;
import lombok.Getter;

/**
 * ProblemDetails is a class that represents detailed information about an error or problem
 * that occurred in the application. It follows the RFC 7807 standard for problem details
 * and includes fields such as type, title, status, detail, instance, code, traceId, timestamp,
 * and a list of violations. This class is used to provide structured error responses
 * in RESTful APIs, allowing clients to understand the nature of the problem and how to address it.
 * 
 * @author  donghyuck, son
 * @since 2025-08-22
 * @version 1.0
 *
 * <pre> 
 * << 개정이력(Modification Information) >>
 *   수정일        수정자           수정내용
 *  ---------    --------    ---------------------------
 * 2025-08-22  donghyuck, son: 최초 생성.
 * </pre>
 */


@Getter
@Builder(toBuilder = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ProblemDetails {

    /** A URI reference that identifies the problem type (RFC 7807). */
    private final String type;           // e.g., "urn:error:error.user.notFound.id" or "about:blank"

    /** A short, human-readable summary of the problem type. */
    private final String title;          // e.g., "Not Found"

    /** The HTTP status code generated by the origin server for this occurrence of the problem. */
    private final Integer status;        // e.g., 404

    /** A human-readable explanation specific to this occurrence of the problem. */
    private final String detail;         // localized message

    /** A URI reference that identifies the specific occurrence of the problem. */
    private final String instance;       // request path, e.g., "/users/1"

    /** ---- Extensions (non-standard but practical) ---- */
    private final String code;           // i18n key / internal error code
    private final String traceId;        // correlation id (from MDC or filter)
    
    private final Locale locale;
    
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    private final OffsetDateTime timestamp;

    private final List<Violation> violations; // field-level violations (validation, etc.)

    @Getter
    @Builder
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class Violation {
        private final String field;
        private final Object rejectedValue;
        private final String code;       // e.g., "NotNull", "Size"
        private final String message;    // localized field error
    }
}
