-- =================================================
-- PACKAGE: WORKSPACE WIKI SERVICE
-- CREATE WORKSPACE WIKI PAGE/REVISION TABLES
-- =================================================

CREATE TABLE TB_APPLICATION_WORKSPACE_WIKI_PAGE (
    PAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    WORKSPACE_ID BIGINT NOT NULL,
    SLUG VARCHAR(200) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CURRENT_REVISION_ID BIGINT NULL,
    CURRENT_REVISION_NO INTEGER NOT NULL DEFAULT 0,
    ARCHIVED BOOLEAN NOT NULL DEFAULT FALSE,
    ARCHIVED_AT DATETIME(6) NULL,
    ARCHIVED_BY BIGINT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT UK_WORKSPACE_WIKI_PAGE_WORKSPACE_SLUG UNIQUE (WORKSPACE_ID, SLUG),
    INDEX IDX_WORKSPACE_WIKI_PAGE_WORKSPACE (WORKSPACE_ID),
    INDEX IDX_WORKSPACE_WIKI_PAGE_CURRENT_REV (CURRENT_REVISION_ID),
    INDEX IDX_WORKSPACE_WIKI_PAGE_ARCHIVED (ARCHIVED)
);

CREATE TABLE TB_APPLICATION_WORKSPACE_WIKI_PAGE_REVISION (
    REVISION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PAGE_ID BIGINT NOT NULL,
    WORKSPACE_ID BIGINT NOT NULL,
    REVISION_NO INTEGER NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    MARKDOWN TEXT NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT UK_WORKSPACE_WIKI_REVISION_PAGE_NO UNIQUE (PAGE_ID, REVISION_NO),
    CONSTRAINT FK_WORKSPACE_WIKI_REVISION_PAGE FOREIGN KEY (PAGE_ID)
        REFERENCES TB_APPLICATION_WORKSPACE_WIKI_PAGE (PAGE_ID),
    INDEX IDX_WORKSPACE_WIKI_REVISION_PAGE (PAGE_ID),
    INDEX IDX_WORKSPACE_WIKI_REVISION_WORKSPACE (WORKSPACE_ID),
    INDEX IDX_WORKSPACE_WIKI_REVISION_CREATED_AT (CREATED_AT)
);
