package studio.one.platform.team.application.usecase;

import java.util.List;

public interface TeamMigrationKnowledgePort {

    KnowledgeSnapshot captureBeforeSnapshot(List<Long> sourceRootWorkspaceIds);

    /**
     * Builds Team-owned manifest/corpus state from existing sources. Implementations must not
     * delete or copy attachment binaries, Wiki/Web source revisions, vectors, or RAG jobs.
     */
    void attachExistingKnowledge(
            String runId,
            Long targetTeamId,
            List<Long> sourceRootWorkspaceIds,
            String snapshotReference);

    MigrationVerification verifyExistingKnowledge(
            String runId,
            Long targetTeamId,
            List<Long> sourceRootWorkspaceIds,
            String snapshotReference);

    /** Removes only Team state generated by this migration; source files and vectors are immutable. */
    void rollbackGeneratedState(String runId, Long targetTeamId, String snapshotReference);

    record KnowledgeSnapshot(
            String reference,
            long attachmentCount,
            long wikiCount,
            long webSourceCount,
            long vectorCount,
            String sourceChecksum) {
    }

    record MigrationVerification(boolean matches, String details) {
    }
}
