CREATE TABLE IF NOT EXISTS TB_APPLICATION_COMPANY_MEMBER_KEY (
    KEY_ID BIGSERIAL PRIMARY KEY,
    COMPANY_ID BIGINT NOT NULL,
    ROLE VARCHAR(30) NOT NULL,
    KEY_HASH VARCHAR(64) NOT NULL UNIQUE,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    EXPIRES_AT TIMESTAMPTZ,
    MAX_USES INTEGER,
    USED_COUNT INTEGER NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CREATED_BY BIGINT,
    UPDATED_AT TIMESTAMPTZ,
    UPDATED_BY BIGINT,
    CONSTRAINT FK_COMPANY_MEMBER_KEY_COMPANY
        FOREIGN KEY (COMPANY_ID)
        REFERENCES TB_APPLICATION_COMPANY(COMPANY_ID)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_COMPANY_MEMBER_KEY_COMPANY_STATUS
    ON TB_APPLICATION_COMPANY_MEMBER_KEY (COMPANY_ID, STATUS);

CREATE TABLE IF NOT EXISTS TB_APPLICATION_COMPANY_JOIN_REQUEST (
    REQUEST_ID BIGSERIAL PRIMARY KEY,
    COMPANY_ID BIGINT NOT NULL,
    KEY_ID BIGINT NOT NULL,
    USER_ID BIGINT,
    REQUEST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    MESSAGE VARCHAR(1000),
    REQUESTED_ROLE VARCHAR(30) NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    REQUESTED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    REQUESTED_BY BIGINT,
    DECIDED_AT TIMESTAMPTZ,
    DECIDED_BY BIGINT,
    UPDATED_AT TIMESTAMPTZ,
    CONSTRAINT FK_COMPANY_JOIN_REQUEST_COMPANY
        FOREIGN KEY (COMPANY_ID)
        REFERENCES TB_APPLICATION_COMPANY(COMPANY_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_COMPANY_JOIN_REQUEST_KEY
        FOREIGN KEY (KEY_ID)
        REFERENCES TB_APPLICATION_COMPANY_MEMBER_KEY(KEY_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_COMPANY_JOIN_REQUEST_USER
        FOREIGN KEY (USER_ID)
        REFERENCES TB_APPLICATION_USER(USER_ID)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IDX_COMPANY_JOIN_REQUEST_COMPANY_STATUS
    ON TB_APPLICATION_COMPANY_JOIN_REQUEST (COMPANY_ID, STATUS, REQUESTED_AT DESC);

CREATE INDEX IF NOT EXISTS IDX_COMPANY_JOIN_REQUEST_USER
    ON TB_APPLICATION_COMPANY_JOIN_REQUEST (USER_ID);

CREATE UNIQUE INDEX IF NOT EXISTS UK_COMPANY_JOIN_REQUEST_PENDING_USER
    ON TB_APPLICATION_COMPANY_JOIN_REQUEST (COMPANY_ID, USER_ID)
    WHERE STATUS = 'PENDING' AND USER_ID IS NOT NULL;
