ai-chat=studio.one.platform.ai.web.controller.ChatController
ai-rag=studio.one.platform.ai.web.controller.RagIndexJobController
ai-vector=studio.one.platform.ai.web.controller.VectorController
ai-vector-visualization=studio.one.platform.ai.web.controller.VectorVisualizationMgmtController
team-rag=studio.one.platform.ai.web.controller.TeamKnowledgeSourceController
