CREATE TABLE IF NOT EXISTS TB_PLATFORM_TEAM (
    TEAM_ID BIGSERIAL PRIMARY KEY,
    COMPANY_ID BIGINT,
    NAME VARCHAR(255) NOT NULL,
    SLUG VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    VISIBILITY VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    JOIN_POLICY VARCHAR(20) NOT NULL DEFAULT 'INVITE_ONLY',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    RAG_ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    RAG_REPLY_MODE VARCHAR(20) NOT NULL DEFAULT 'MENTION',
    PERMISSION_VERSION BIGINT NOT NULL DEFAULT 1,
    ARCHIVED_AT TIMESTAMPTZ,
    ARCHIVED_BY BIGINT,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UK_PLATFORM_TEAM_SLUG UNIQUE (SLUG),
    CONSTRAINT FK_PLATFORM_TEAM_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES TB_APPLICATION_COMPANY(COMPANY_ID)
);

CREATE INDEX IF NOT EXISTS IDX_PLATFORM_TEAM_COMPANY ON TB_PLATFORM_TEAM (COMPANY_ID);
CREATE INDEX IF NOT EXISTS IDX_PLATFORM_TEAM_DISCOVERY ON TB_PLATFORM_TEAM (VISIBILITY, STATUS);

CREATE TABLE IF NOT EXISTS TB_PLATFORM_TEAM_MEMBER (
    MEMBER_ID BIGSERIAL PRIMARY KEY,
    TEAM_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY BIGINT NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UK_PLATFORM_TEAM_MEMBER UNIQUE (TEAM_ID, USER_ID),
    CONSTRAINT FK_PLATFORM_TEAM_MEMBER_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TB_PLATFORM_TEAM(TEAM_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_PLATFORM_TEAM_MEMBER_USER ON TB_PLATFORM_TEAM_MEMBER (USER_ID, STATUS);
