CREATE TABLE IF NOT EXISTS TB_PLATFORM_TEAM_JOIN_REQUEST (
    REQUEST_ID BIGSERIAL PRIMARY KEY,
    TEAM_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    REQUESTED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    RESOLVED_AT TIMESTAMPTZ,
    RESOLVED_BY BIGINT,
    CONSTRAINT UK_PLATFORM_TEAM_JOIN_REQUEST_USER UNIQUE (TEAM_ID, USER_ID),
    CONSTRAINT FK_PLATFORM_TEAM_JOIN_REQUEST_TEAM FOREIGN KEY (TEAM_ID)
        REFERENCES TB_PLATFORM_TEAM(TEAM_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_PLATFORM_TEAM_JOIN_REQUEST_STATUS
    ON TB_PLATFORM_TEAM_JOIN_REQUEST (TEAM_ID, STATUS, REQUESTED_AT);
