-- =================================================
-- PACKAGE: WORKSPACE WIKI SERVICE
-- CREATE WORKSPACE WIKI PAGE/REVISION TABLES
-- =================================================

CREATE TABLE TB_APPLICATION_WORKSPACE_WIKI_PAGE (
    PAGE_ID BIGSERIAL PRIMARY KEY,
    WORKSPACE_ID BIGINT NOT NULL,
    SLUG VARCHAR(200) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CURRENT_REVISION_ID BIGINT,
    CURRENT_REVISION_NO INTEGER NOT NULL DEFAULT 0,
    ARCHIVED BOOLEAN NOT NULL DEFAULT FALSE,
    ARCHIVED_AT TIMESTAMPTZ,
    ARCHIVED_BY BIGINT,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UK_WORKSPACE_WIKI_PAGE_WORKSPACE_SLUG UNIQUE (WORKSPACE_ID, SLUG)
);

COMMENT ON TABLE TB_APPLICATION_WORKSPACE_WIKI_PAGE IS 'Workspace wiki page table';

CREATE TABLE TB_APPLICATION_WORKSPACE_WIKI_PAGE_REVISION (
    REVISION_ID BIGSERIAL PRIMARY KEY,
    PAGE_ID BIGINT NOT NULL,
    WORKSPACE_ID BIGINT NOT NULL,
    REVISION_NO INTEGER NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    MARKDOWN TEXT NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT UK_WORKSPACE_WIKI_REVISION_PAGE_NO UNIQUE (PAGE_ID, REVISION_NO),
    CONSTRAINT FK_WORKSPACE_WIKI_REVISION_PAGE FOREIGN KEY (PAGE_ID)
        REFERENCES TB_APPLICATION_WORKSPACE_WIKI_PAGE (PAGE_ID)
);

COMMENT ON TABLE TB_APPLICATION_WORKSPACE_WIKI_PAGE_REVISION IS 'Workspace wiki page revision table';

CREATE INDEX IDX_WORKSPACE_WIKI_PAGE_WORKSPACE ON TB_APPLICATION_WORKSPACE_WIKI_PAGE (WORKSPACE_ID);
CREATE INDEX IDX_WORKSPACE_WIKI_PAGE_CURRENT_REV ON TB_APPLICATION_WORKSPACE_WIKI_PAGE (CURRENT_REVISION_ID);
CREATE INDEX IDX_WORKSPACE_WIKI_PAGE_ARCHIVED ON TB_APPLICATION_WORKSPACE_WIKI_PAGE (ARCHIVED);
CREATE INDEX IDX_WORKSPACE_WIKI_REVISION_PAGE ON TB_APPLICATION_WORKSPACE_WIKI_PAGE_REVISION (PAGE_ID);
CREATE INDEX IDX_WORKSPACE_WIKI_REVISION_WORKSPACE ON TB_APPLICATION_WORKSPACE_WIKI_PAGE_REVISION (WORKSPACE_ID);
CREATE INDEX IDX_WORKSPACE_WIKI_REVISION_CREATED_AT ON TB_APPLICATION_WORKSPACE_WIKI_PAGE_REVISION (CREATED_AT);
