-- =================================================
-- PACKAGE: MAIL SERVICE
-- CREATE : 2025.12.10
-- UPDATE :
-- =================================================

CREATE TABLE TB_APPLICATION_MAIL_MESSAGE (
    MAIL_ID BIGSERIAL PRIMARY KEY, -- 메일 ID
    FOLDER VARCHAR(128) NOT NULL, -- 폴더 이름
    UID BIGINT NOT NULL, -- IMAP UID
    MESSAGE_ID VARCHAR(255), -- Message-ID 헤더
    SUBJECT TEXT, -- 제목
    FROM_ADDRESS VARCHAR(512), -- 발신자
    TO_ADDRESS VARCHAR(1024), -- 수신자(TO)
    CC_ADDRESS VARCHAR(1024), -- 수신자(CC)
    BCC_ADDRESS VARCHAR(1024), -- 수신자(BCC)
    SENT_AT TIMESTAMPTZ, -- 발신 시간
    RECEIVED_AT TIMESTAMPTZ, -- 수신 시간
    FLAGS VARCHAR(255), -- 플래그 문자열
    BODY TEXT, -- 본문
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(), -- 생성일
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW() -- 수정일
);

COMMENT ON TABLE TB_APPLICATION_MAIL_MESSAGE IS 'IMAP 메일 동기화 테이블';
CREATE UNIQUE INDEX TB_APPLICATION_MAIL_MESSAGE_UIDX1 ON TB_APPLICATION_MAIL_MESSAGE (FOLDER, UID);
CREATE INDEX IDX_TB_APPLICATION_MAIL_MESSAGE_MESSAGEID ON TB_APPLICATION_MAIL_MESSAGE (MESSAGE_ID);

CREATE TABLE TB_APPLICATION_MAIL_ATTACHMENT (
    ATTACHMENT_ID BIGSERIAL PRIMARY KEY, -- 첨부 ID
    MAIL_ID BIGINT NOT NULL, -- 메일 ID
    FILENAME VARCHAR(512), -- 파일 이름
    CONTENT_TYPE VARCHAR(255), -- 콘텐츠 타입
    SIZE BIGINT, -- 크기
    CONTENT BYTEA, -- 바이너리
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(), -- 생성일
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW() -- 수정일
);

COMMENT ON TABLE TB_APPLICATION_MAIL_ATTACHMENT IS 'IMAP 메일 첨부';
CREATE INDEX IDX_TB_APPLICATION_MAIL_ATTACHMENT_MAIL ON TB_APPLICATION_MAIL_ATTACHMENT (MAIL_ID);
ALTER TABLE TB_APPLICATION_MAIL_ATTACHMENT
    ADD CONSTRAINT FK_MAIL_ATTACHMENT
    FOREIGN KEY (MAIL_ID)
    REFERENCES TB_APPLICATION_MAIL_MESSAGE (MAIL_ID)
    ON DELETE CASCADE;

CREATE TABLE TB_APPLICATION_MAIL_SYNC_LOG (
    LOG_ID BIGSERIAL PRIMARY KEY, -- 로그 ID
    STARTED_AT TIMESTAMPTZ NOT NULL, -- 시작 시간
    FINISHED_AT TIMESTAMPTZ, -- 종료 시간
    PROCESSED INTEGER DEFAULT 0, -- 처리된 건수
    SUCCEEDED INTEGER DEFAULT 0, -- 성공 건수
    FAILED INTEGER DEFAULT 0, -- 실패 건수
    STATUS VARCHAR(50), -- 상태 (running/completed/failed 등)
    MESSAGE VARCHAR(1000), -- 결과 메시지
    TRIGGERED_BY VARCHAR(100) -- 실행 주체(스케줄/수동 등)
);

COMMENT ON TABLE TB_APPLICATION_MAIL_SYNC_LOG IS '메일 동기화 이력';
CREATE INDEX IDX_TB_APPLICATION_MAIL_SYNC_LOG_STARTED ON TB_APPLICATION_MAIL_SYNC_LOG (STARTED_AT DESC);

CREATE TABLE TB_APPLICATION_MAIL_PROPERTY (
    MAIL_ID BIGINT NOT NULL, -- 메일 ID
    PROPERTY_NAME VARCHAR(100), -- 프로퍼티 이름
    PROPERTY_VALUE VARCHAR(1024), -- 프로퍼티 값
    PRIMARY KEY (MAIL_ID, PROPERTY_NAME)
);

COMMENT ON TABLE TB_APPLICATION_MAIL_PROPERTY IS 'IMAP 메일 프로퍼티';
ALTER TABLE TB_APPLICATION_MAIL_PROPERTY
    ADD CONSTRAINT FK_MAIL_PROPERTY
    FOREIGN KEY (MAIL_ID)
    REFERENCES TB_APPLICATION_MAIL_MESSAGE (MAIL_ID)
    ON DELETE CASCADE;
