package studio.one.application.webknowledge.application;

import java.time.Instant;

public record WebKnowledgeSourceView(
        String sourceId,
        Long workspaceId,
        String url,
        String canonicalUrl,
        String host,
        String displayName,
        String embeddingDeploymentId,
        String embeddingSpaceId,
        String status,
        String collectionMode,
        String currentRevisionId,
        String currentCorpusRevisionId,
        String revisionStatus,
        String latestRunId,
        boolean crawlTruncated,
        int discoveredCount,
        int fetchedCount,
        int indexedCount,
        int unchangedCount,
        int updatedCount,
        int removedCount,
        int failedCount,
        int skippedCount,
        String title,
        String publisher,
        String language,
        Instant publishedAt,
        Instant modifiedAt,
        Instant retrievedAt,
        String contentPreview,
        String errorCode,
        Instant createdAt,
        Instant updatedAt) {

    public WebKnowledgeSourceView(
            String sourceId,
            Long workspaceId,
            String url,
            String canonicalUrl,
            String host,
            String displayName,
            String embeddingDeploymentId,
            String embeddingSpaceId,
            String status,
            String currentRevisionId,
            String revisionStatus,
            String title,
            String publisher,
            String language,
            Instant publishedAt,
            Instant modifiedAt,
            Instant retrievedAt,
            String contentPreview,
            String errorCode,
            Instant createdAt,
            Instant updatedAt) {
        this(
                sourceId,
                workspaceId,
                url,
                canonicalUrl,
                host,
                displayName,
                embeddingDeploymentId,
                embeddingSpaceId,
                status,
                WebKnowledgeCollectionMode.SINGLE_PAGE.name(),
                currentRevisionId,
                null,
                revisionStatus,
                null,
                false,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                title,
                publisher,
                language,
                publishedAt,
                modifiedAt,
                retrievedAt,
                contentPreview,
                errorCode,
                createdAt,
                updatedAt);
    }
}
