package studio.one.platform.markdown.web;

import jakarta.validation.constraints.Positive;

public record MarkdownDocumentRequest(
                @Positive long attachmentId,
                boolean runChunking,
                boolean runRagIndex,
                boolean runSkillExtraction,
                boolean force,
                String chunkingStrategy,
                Integer chunkMaxSize,
                Integer chunkOverlap,
                String chunkUnit,
                String blockifyLlmProvider,
                String blockifyLlmModel,
                Boolean blockifyPiiMaskingEnabled,
                String embeddingProfileId,
                String embeddingProvider,
                String embeddingModel,
                Integer embeddingDimension,
                boolean useLlmKeywordExtraction,
                String skillExtractionMode,
                boolean generateSkillEmbeddings,
                String skillEmbeddingProvider,
                String skillEmbeddingModel,
                Integer skillEmbeddingDimension,
                Boolean ocrRequired,
                String ocrLanguage,
                String ocrMode,
                Boolean mathVisionCorrection,
                String documentProfile) {

        public MarkdownDocumentRequest(
                        long attachmentId,
                        boolean runChunking,
                        boolean runRagIndex,
                        boolean runSkillExtraction,
                        boolean force,
                        String chunkingStrategy,
                        Integer chunkMaxSize,
                        Integer chunkOverlap,
                        String chunkUnit,
                        String blockifyLlmProvider,
                        String blockifyLlmModel,
                        Boolean blockifyPiiMaskingEnabled,
                        String embeddingProfileId,
                        String embeddingProvider,
                        String embeddingModel,
                        Integer embeddingDimension,
                        boolean useLlmKeywordExtraction,
                        String skillExtractionMode,
                        boolean generateSkillEmbeddings,
                        String skillEmbeddingProvider,
                        String skillEmbeddingModel,
                        Integer skillEmbeddingDimension,
                        Boolean ocrRequired,
                        String ocrLanguage,
                        String ocrMode,
                        Boolean mathVisionCorrection) {
                this(attachmentId, runChunking, runRagIndex, runSkillExtraction, force,
                                chunkingStrategy, chunkMaxSize, chunkOverlap, chunkUnit,
                                blockifyLlmProvider, blockifyLlmModel, blockifyPiiMaskingEnabled,
                                embeddingProfileId, embeddingProvider, embeddingModel, embeddingDimension,
                                useLlmKeywordExtraction, skillExtractionMode, generateSkillEmbeddings,
                                skillEmbeddingProvider, skillEmbeddingModel, skillEmbeddingDimension,
                                ocrRequired, ocrLanguage, ocrMode, mathVisionCorrection, null);
        }
}
