package studio.one.platform.ai.service.pipeline;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import tools.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import studio.one.platform.chunking.artifact.ChunkSet;
import studio.one.platform.chunking.artifact.ChunkSetItem;
import studio.one.platform.chunking.artifact.ChunkSetQualityStatus;
import studio.one.platform.chunking.artifact.ChunkSetStatus;

class JdbcChunkSetStoreTest {

    private JdbcChunkSetStore store;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:chunk-set-" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE tb_ai_chunk_set (
                  chunk_set_id VARCHAR(200) PRIMARY KEY,
                  object_type VARCHAR(100) NOT NULL,
                  object_id VARCHAR(150) NOT NULL,
                  document_id VARCHAR(200) NOT NULL,
                  source_revision_id VARCHAR(200) NOT NULL,
                  source_content_hash VARCHAR(128) NOT NULL,
                  strategy VARCHAR(100) NOT NULL,
                  strategy_hash VARCHAR(128) NOT NULL,
                  chunk_unit VARCHAR(30),
                  max_size INT,
                  overlap_size INT,
                  status VARCHAR(30) NOT NULL,
                  quality_status VARCHAR(30) NOT NULL,
                  quality_issues CLOB,
                  metadata CLOB,
                  created_at TIMESTAMP NOT NULL,
                  updated_at TIMESTAMP NOT NULL
                )
                """);
        jdbc.execute("""
                CREATE TABLE tb_ai_chunk_item (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  chunk_set_id VARCHAR(200) NOT NULL,
                  chunk_index INT NOT NULL,
                  chunk_id VARCHAR(200) NOT NULL,
                  text CLOB NOT NULL,
                  content_hash VARCHAR(128) NOT NULL,
                  metadata CLOB,
                  created_at TIMESTAMP NOT NULL,
                  CONSTRAINT fk_chunk_set FOREIGN KEY (chunk_set_id)
                    REFERENCES tb_ai_chunk_set(chunk_set_id) ON DELETE CASCADE
                )
                """);
        store = new JdbcChunkSetStore(new NamedParameterJdbcTemplate(dataSource), new ObjectMapper(), null);
    }

    @Test
    void savesAndRestoresChunkSetWithoutChangingChunkContentOrMetadata() {
        ChunkSet source = chunkSet();

        store.save(source);

        ChunkSet restored = store.findById(source.chunkSetId()).orElseThrow();
        assertThat(restored.sourceRevisionId()).isEqualTo("mrev-1");
        assertThat(restored.items()).extracting(ChunkSetItem::text)
                .containsExactly("첫 번째 본문", "$x^2+1$");
        assertThat(restored.items().get(1).metadata())
                .containsEntry("page", 2)
                .containsEntry("sourceRef", "page[2]/block[1]");
        assertThat(store.findLatest("attachment", "6", "mdoc-1", "mrev-1"))
                .contains(restored);
    }

    @Test
    void invalidatesStoredChunkSetWithoutDeletingItems() {
        ChunkSet source = chunkSet();
        store.save(source);

        store.invalidate(source.chunkSetId());

        ChunkSet restored = store.findById(source.chunkSetId()).orElseThrow();
        assertThat(restored.status()).isEqualTo(ChunkSetStatus.INVALIDATED);
        assertThat(restored.items()).hasSize(2);
    }

    @Test
    void writesChunkSetItemsInConfiguredBatches() {
        NamedParameterJdbcTemplate template = mock(NamedParameterJdbcTemplate.class);
        JdbcChunkSetStore batchStore = new JdbcChunkSetStore(template, new ObjectMapper(), 2, null);

        batchStore.save(chunkSet(5));

        ArgumentCaptor<MapSqlParameterSource[]> batches = ArgumentCaptor.forClass(MapSqlParameterSource[].class);
        verify(template, times(3)).batchUpdate(anyString(), batches.capture());
        assertThat(batches.getAllValues()).extracting(batch -> batch.length).containsExactly(2, 2, 1);
    }

    private ChunkSet chunkSet() {
        Instant now = Instant.parse("2026-07-17T00:00:00Z");
        return new ChunkSet(
                "cset-1", "attachment", "6", "mdoc-1", "mrev-1", "source-hash",
                "structure-based", "strategy-hash", "CHARACTER", 1200, 150,
                ChunkSetStatus.READY, ChunkSetQualityStatus.REVIEW_REQUIRED,
                List.of("PAGE_PROVENANCE_REVIEW_REQUIRED"), Map.of("ragIndexEligible", true),
                List.of(
                        new ChunkSetItem(0, "chunk-1", "첫 번째 본문", "hash-1", Map.of("page", 1)),
                        new ChunkSetItem(1, "chunk-2", "$x^2+1$", "hash-2",
                                Map.of("page", 2, "sourceRef", "page[2]/block[1]"))),
                now, now);
    }

    private ChunkSet chunkSet(int itemCount) {
        Instant now = Instant.parse("2026-07-17T00:00:00Z");
        List<ChunkSetItem> items = new ArrayList<>(itemCount);
        for (int index = 0; index < itemCount; index++) {
            items.add(new ChunkSetItem(index, "chunk-" + index, "content-" + index,
                    "hash-" + index, Map.of("page", index + 1)));
        }
        return new ChunkSet(
                "cset-batch", "attachment", "5", "mdoc-5", "mrev-5", "source-hash",
                "structure-based", "strategy-hash", "CHARACTER", 6000, 150,
                ChunkSetStatus.READY, ChunkSetQualityStatus.VALID,
                List.of(), Map.of("ragIndexEligible", true), items, now, now);
    }
}
