CREATE TABLE IF NOT EXISTS TB_PLATFORM_TEAM_MIGRATION_RUN (
    RUN_ID VARCHAR(36) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(128) NOT NULL,
    TARGET_TEAM_ID BIGINT NOT NULL,
    SOURCE_ROOT_IDS VARCHAR(4000) NOT NULL,
    STATUS VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
    BEFORE_SNAPSHOT_REF LONGTEXT NULL,
    WORKSPACE_SNAPSHOT_REF LONGTEXT NULL,
    KNOWLEDGE_SNAPSHOT_REF LONGTEXT NULL,
    WORKSPACE_COUNT BIGINT NOT NULL DEFAULT 0,
    MEMBER_COUNT BIGINT NOT NULL DEFAULT 0,
    ATTACHMENT_COUNT BIGINT NOT NULL DEFAULT 0,
    WIKI_COUNT BIGINT NOT NULL DEFAULT 0,
    WEB_SOURCE_COUNT BIGINT NOT NULL DEFAULT 0,
    VECTOR_COUNT BIGINT NOT NULL DEFAULT 0,
    SOURCE_CHECKSUM VARCHAR(128) NULL,
    FAILURE_MESSAGE VARCHAR(2000) NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LOCK_VERSION BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (RUN_ID),
    UNIQUE KEY UK_PLATFORM_TEAM_MIGRATION_IDEMPOTENCY (IDEMPOTENCY_KEY),
    KEY IDX_PLATFORM_TEAM_MIGRATION_TEAM_STATUS (TARGET_TEAM_ID, STATUS),
    CONSTRAINT FK_PLATFORM_TEAM_MIGRATION_TARGET FOREIGN KEY (TARGET_TEAM_ID) REFERENCES TB_PLATFORM_TEAM(TEAM_ID)
);

CREATE TABLE IF NOT EXISTS TB_PLATFORM_TEAM_MIGRATION_LOCK (
    LOCK_KEY VARCHAR(128) NOT NULL,
    RUN_ID VARCHAR(36) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LOCK_KEY),
    KEY IDX_PLATFORM_TEAM_MIGRATION_LOCK_RUN (RUN_ID),
    CONSTRAINT FK_PLATFORM_TEAM_MIGRATION_LOCK_RUN FOREIGN KEY (RUN_ID)
        REFERENCES TB_PLATFORM_TEAM_MIGRATION_RUN(RUN_ID) ON DELETE CASCADE
);
