package studio.one.platform.skillgraph.domain.model;

public enum SkillGraphBatchJobType {
    CANDIDATE_EMBEDDING,
    DICTIONARY_EMBEDDING,
    CANDIDATE_RECOMMENDATION,
    SKILL_CLUSTER_GENERATION,
    PROJECTION_GENERATION,
    SKILL_CLUSTERING,
    CATEGORY_CANDIDATE_GENERATION
}
