-- =================================================
-- PACKAGE: TEMPLATE SERVICE
-- CREATE : 2025.12.08
-- UPDATE :
-- =================================================

CREATE TABLE TB_APPLICATION_TEMPLATE (
    TEMPLATE_ID BIGSERIAL PRIMARY KEY, -- 템플릿 ID
    OBJECT_TYPE INTEGER NOT NULL, -- 객체 타입
    OBJECT_ID BIGINT NOT NULL, -- 객체 ID
    NAME VARCHAR(255) NOT NULL, -- 템플릿 이름
    DISPLAY_NAME VARCHAR(255), -- 출력 이름
    DESCRIPTION VARCHAR(1000), -- 설명
    SUBJECT VARCHAR(500), -- 제목 템플릿
    BODY TEXT, -- 본문 템플릿
    CREATED_BY BIGINT NOT NULL DEFAULT 0, -- 생성자
    UPDATED_BY BIGINT NOT NULL DEFAULT 0, -- 수정자
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(), -- 생성일
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW() -- 수정일
);

COMMENT ON TABLE TB_APPLICATION_TEMPLATE IS '애플리케이션 템플릿 테이블';
CREATE UNIQUE INDEX TB_APPLICATION_TEMPLATE_UIDX1 ON TB_APPLICATION_TEMPLATE (NAME);
CREATE INDEX IDX_TB_APPLICATION_TEMPLATE_OBJECT ON TB_APPLICATION_TEMPLATE (OBJECT_TYPE, OBJECT_ID);

CREATE TABLE TB_APPLICATION_TEMPLATE_PROPERTY (
    TEMPLATE_ID BIGINT NOT NULL, -- 템플릿 ID
    PROPERTY_NAME VARCHAR(100), -- 프로퍼티 이름
    PROPERTY_VALUE VARCHAR(1024), -- 프로퍼티 값
    PRIMARY KEY (TEMPLATE_ID, PROPERTY_NAME)
);

COMMENT ON TABLE TB_APPLICATION_TEMPLATE_PROPERTY IS '애플리케이션 템플릿 프로퍼티';
ALTER TABLE TB_APPLICATION_TEMPLATE_PROPERTY
    ADD CONSTRAINT FK_TEMPLATE_PROPERTY
    FOREIGN KEY (TEMPLATE_ID)
    REFERENCES TB_APPLICATION_TEMPLATE (TEMPLATE_ID)
    ON DELETE CASCADE;
