CREATE TABLE TB_APPLICATION_PROPERTY (
    PROPERTY_NAME VARCHAR(100) NOT NULL,         -- 프로퍼티 이름
    PROPERTY_VALUE VARCHAR(1024) NOT NULL,       -- 프로퍼티 값
    CONSTRAINT TB_APPLICATION_PROPERTY_PK PRIMARY KEY (PROPERTY_NAME)
);

COMMENT ON TABLE TB_APPLICATION_PROPERTY IS '애플리케이션 전역 프로퍼티';
COMMENT ON COLUMN TB_APPLICATION_PROPERTY.PROPERTY_NAME IS '프로퍼티 이름';
COMMENT ON COLUMN TB_APPLICATION_PROPERTY.PROPERTY_VALUE IS '프로퍼티 값';
