CREATE TABLE IF NOT EXISTS web_knowledge_source (
    source_id VARCHAR(80) NOT NULL PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    input_url VARCHAR(2048) NOT NULL,
    normalized_url VARCHAR(2048) NOT NULL,
    normalized_url_hash VARCHAR(64) NOT NULL,
    active_dedupe_key VARCHAR(256) NULL,
    canonical_url VARCHAR(2048) NULL,
    source_host VARCHAR(255) NOT NULL,
    display_name VARCHAR(300) NULL,
    embedding_deployment_id VARCHAR(160) NOT NULL,
    embedding_space_id VARCHAR(200) NULL,
    current_revision_id VARCHAR(80) NULL,
    status VARCHAR(32) NOT NULL,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(160) NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    INDEX idx_web_knowledge_source_workspace (workspace_id, archived, updated_at),
    INDEX idx_web_knowledge_source_lookup (workspace_id, normalized_url_hash, embedding_deployment_id, archived),
    UNIQUE INDEX uk_web_knowledge_source_active (workspace_id, active_dedupe_key)
);

CREATE TABLE IF NOT EXISTS web_knowledge_revision (
    revision_id VARCHAR(80) NOT NULL PRIMARY KEY,
    source_id VARCHAR(80) NOT NULL,
    rag_job_id VARCHAR(80) NULL,
    status VARCHAR(32) NOT NULL,
    title VARCHAR(500) NULL,
    publisher VARCHAR(300) NULL,
    language_code VARCHAR(32) NULL,
    published_at TIMESTAMP(6) NULL,
    source_modified_at TIMESTAMP(6) NULL,
    retrieved_at TIMESTAMP(6) NULL,
    etag VARCHAR(500) NULL,
    last_modified VARCHAR(500) NULL,
    content_type VARCHAR(160) NULL,
    content_length BIGINT NULL,
    content_hash VARCHAR(64) NULL,
    normalized_snapshot LONGTEXT NULL,
    content_preview VARCHAR(500) NULL,
    metadata_json LONGTEXT NULL,
    error_code VARCHAR(80) NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_web_knowledge_revision_source FOREIGN KEY (source_id)
        REFERENCES web_knowledge_source(source_id),
    INDEX idx_web_knowledge_revision_source (source_id, created_at),
    INDEX idx_web_knowledge_revision_status (status, updated_at)
);
