#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"
export PADDLEOCR_WORKER_HOST="${PADDLEOCR_WORKER_HOST:-0.0.0.0}"
export PADDLEOCR_WORKER_PORT="${PADDLEOCR_WORKER_PORT:-8603}"
export PADDLEOCR_MAX_UPLOAD_BYTES="${PADDLEOCR_MAX_UPLOAD_BYTES:-52428800}"
export PADDLEOCR_MAX_PAGES_PER_REQUEST="${PADDLEOCR_MAX_PAGES_PER_REQUEST:-8}"
export PADDLEOCR_MAX_RENDER_PIXELS="${PADDLEOCR_MAX_RENDER_PIXELS:-25000000}"
export PADDLEOCR_DPI="${PADDLEOCR_DPI:-180}"
export PADDLEOCR_LANGUAGE="${PADDLEOCR_LANGUAGE:-korean}"
export UVICORN_WORKERS="${UVICORN_WORKERS:-1}"
export LOG_LEVEL="${LOG_LEVEL:-info}"

exec .venv/bin/python -m uvicorn app.main:app \
  --host "$PADDLEOCR_WORKER_HOST" \
  --port "$PADDLEOCR_WORKER_PORT" \
  --workers "$UVICORN_WORKERS" \
  --log-level "$LOG_LEVEL"
