CREATE TABLE IF NOT EXISTS TB_PLATFORM_TEAM_JOIN_REQUEST (
    REQUEST_ID BIGINT NOT NULL AUTO_INCREMENT,
    TEAM_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    REQUESTED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RESOLVED_AT TIMESTAMP NULL,
    RESOLVED_BY BIGINT NULL,
    PRIMARY KEY (REQUEST_ID),
    UNIQUE KEY UK_PLATFORM_TEAM_JOIN_REQUEST_USER (TEAM_ID, USER_ID),
    KEY IDX_PLATFORM_TEAM_JOIN_REQUEST_STATUS (TEAM_ID, STATUS, REQUESTED_AT),
    CONSTRAINT FK_PLATFORM_TEAM_JOIN_REQUEST_TEAM FOREIGN KEY (TEAM_ID)
        REFERENCES TB_PLATFORM_TEAM(TEAM_ID) ON DELETE CASCADE
);
