-- =================================================
-- PACKAGE: USER
-- CREATE : 2024.9.12
-- UPDATE : 2026.6.10
-- =================================================


-- 사용자 테이블
CREATE TABLE TB_APPLICATION_USER (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    NAME VARCHAR(100),
    NAME_VISIBLE BOOLEAN DEFAULT TRUE,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    EMAIL_VISIBLE BOOLEAN DEFAULT TRUE,
    FAILED_ATTEMPTS INTEGER DEFAULT 0,
    LAST_FAILED_AT DATETIME(6),
    ACCOUNT_LOCKED_UNTIL DATETIME(6) NULL,
    USER_ENABLED BOOLEAN DEFAULT TRUE,
    USER_EXTERNAL BOOLEAN DEFAULT FALSE,
    STATUS INTEGER DEFAULT 0,
    CREATION_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6)
);


CREATE INDEX IDX_APP_USER_LOCKED ON TB_APPLICATION_USER (ACCOUNT_LOCKED_UNTIL);

-- 사용자 속성
CREATE TABLE TB_APPLICATION_USER_PROPERTY (
    USER_ID BIGINT NOT NULL REFERENCES TB_APPLICATION_USER(USER_ID) ON DELETE CASCADE,
    PROPERTY_NAME VARCHAR(100) NOT NULL,
    PROPERTY_VALUE VARCHAR(1024) NOT NULL,
    PRIMARY KEY (USER_ID, PROPERTY_NAME)
);


-- 롤 테이블
CREATE TABLE TB_APPLICATION_ROLE (
    ROLE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(1000) NOT NULL,
    CREATION_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6)
);


-- 사용자 롤 매핑
CREATE TABLE TB_APPLICATION_USER_ROLES (
    USER_ID BIGINT NOT NULL REFERENCES TB_APPLICATION_USER(USER_ID) ON DELETE CASCADE,
    ROLE_ID BIGINT NOT NULL REFERENCES TB_APPLICATION_ROLE(ROLE_ID) ON DELETE CASCADE,
    ASSIGNED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    ASSIGNED_BY VARCHAR(100),
    PRIMARY KEY (USER_ID, ROLE_ID)
);


-- 로그인 토큰
CREATE TABLE TB_APPLICATION_LOGIN_TOKEN (
    UUID VARCHAR(100) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL,
    TOKEN VARCHAR(100) NOT NULL,
    LAST_USE_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);


-- 회사 테이블
CREATE TABLE TB_APPLICATION_COMPANY (
    COMPANY_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    DOMAIN_NAME VARCHAR(100),
    DESCRIPTION VARCHAR(1000),
    CREATION_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6)
);


-- 회사 속성
CREATE TABLE TB_APPLICATION_COMPANY_PROPERTY (
    COMPANY_ID BIGINT NOT NULL REFERENCES TB_APPLICATION_COMPANY(COMPANY_ID) ON DELETE CASCADE,
    PROPERTY_NAME VARCHAR(100) NOT NULL,
    PROPERTY_VALUE VARCHAR(1024) NOT NULL,
    PRIMARY KEY (COMPANY_ID, PROPERTY_NAME)
);


-- 그룹 테이블
CREATE TABLE TB_APPLICATION_GROUP (
    GROUP_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(1000),
    CREATION_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6)
);


-- 그룹 속성
CREATE TABLE TB_APPLICATION_GROUP_PROPERTY (
    GROUP_ID BIGINT NOT NULL REFERENCES TB_APPLICATION_GROUP(GROUP_ID) ON DELETE CASCADE,
    PROPERTY_NAME VARCHAR(100) NOT NULL,
    PROPERTY_VALUE VARCHAR(1024) NOT NULL,
    PRIMARY KEY (GROUP_ID, PROPERTY_NAME)
);


-- 그룹 롤 매핑
CREATE TABLE TB_APPLICATION_GROUP_ROLES (
    GROUP_ID BIGINT NOT NULL REFERENCES TB_APPLICATION_GROUP(GROUP_ID) ON DELETE CASCADE,
    ROLE_ID BIGINT NOT NULL REFERENCES TB_APPLICATION_ROLE(ROLE_ID) ON DELETE CASCADE,
    ASSIGNED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    ASSIGNED_BY VARCHAR(100),
    PRIMARY KEY (GROUP_ID, ROLE_ID)
);


-- 그룹 멤버 매핑
CREATE TABLE TB_APPLICATION_GROUP_MEMBERS (
    GROUP_ID BIGINT NOT NULL REFERENCES TB_APPLICATION_GROUP(GROUP_ID) ON DELETE CASCADE,
    USER_ID BIGINT NOT NULL REFERENCES TB_APPLICATION_USER(USER_ID) ON DELETE CASCADE,
    JOINED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    JOINED_BY VARCHAR(100),
    PRIMARY KEY (GROUP_ID, USER_ID)
);
