ALTER TABLE TB_APPLICATION_COMPANY
    ADD COLUMN STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE TB_APPLICATION_COMPANY
    ADD COLUMN ARCHIVED_AT TIMESTAMPTZ;

ALTER TABLE TB_APPLICATION_COMPANY
    ADD COLUMN ARCHIVED_BY BIGINT;

CREATE TABLE IF NOT EXISTS TB_APPLICATION_COMPANY_MEMBERS (
    COMPANY_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ROLE VARCHAR(30) NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    JOINED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    JOINED_BY BIGINT,
    UPDATED_AT TIMESTAMPTZ,
    UPDATED_BY BIGINT,
    PRIMARY KEY (COMPANY_ID, USER_ID),
    CONSTRAINT FK_APPLICATION_COMPANY_MEMBERS_COMPANY
        FOREIGN KEY (COMPANY_ID)
        REFERENCES TB_APPLICATION_COMPANY(COMPANY_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_APPLICATION_COMPANY_MEMBERS_USER
        FOREIGN KEY (USER_ID)
        REFERENCES TB_APPLICATION_USER(USER_ID)
        ON DELETE CASCADE
);

CREATE INDEX IDX_APPLICATION_COMPANY_MEMBERS_USER
    ON TB_APPLICATION_COMPANY_MEMBERS (USER_ID);

CREATE INDEX IDX_APPLICATION_COMPANY_MEMBERS_COMPANY_ROLE
    ON TB_APPLICATION_COMPANY_MEMBERS (COMPANY_ID, ROLE);
