CREATE TABLE IF NOT EXISTS TB_APPLICATION_COMPANY_PERMISSION_POLICY (
    COMPANY_ID BIGINT NOT NULL,
    ROLE VARCHAR(30) NOT NULL,
    ACTION_NAME VARCHAR(100) NOT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NULL,
    UPDATED_BY BIGINT NULL,
    PRIMARY KEY (COMPANY_ID, ROLE, ACTION_NAME),
    CONSTRAINT FK_COMPANY_PERMISSION_POLICY_COMPANY
        FOREIGN KEY (COMPANY_ID)
        REFERENCES TB_APPLICATION_COMPANY (COMPANY_ID)
        ON DELETE CASCADE
);

CREATE INDEX IX_COMPANY_PERMISSION_POLICY_COMPANY_ROLE
    ON TB_APPLICATION_COMPANY_PERMISSION_POLICY (COMPANY_ID, ROLE);
