CREATE TABLE IF NOT EXISTS TB_APPLICATION_COMPANY_MEMBER_KEY (
    KEY_ID BIGINT NOT NULL AUTO_INCREMENT,
    COMPANY_ID BIGINT NOT NULL,
    ROLE VARCHAR(30) NOT NULL,
    KEY_HASH VARCHAR(64) NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    EXPIRES_AT DATETIME(6),
    MAX_USES INTEGER,
    USED_COUNT INTEGER NOT NULL DEFAULT 0,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CREATED_BY BIGINT,
    UPDATED_AT DATETIME(6),
    UPDATED_BY BIGINT,
    PRIMARY KEY (KEY_ID),
    CONSTRAINT UK_COMPANY_MEMBER_KEY_HASH UNIQUE (KEY_HASH),
    CONSTRAINT FK_COMPANY_MEMBER_KEY_COMPANY
        FOREIGN KEY (COMPANY_ID)
        REFERENCES TB_APPLICATION_COMPANY(COMPANY_ID)
        ON DELETE CASCADE
);

CREATE INDEX IDX_COMPANY_MEMBER_KEY_COMPANY_STATUS
    ON TB_APPLICATION_COMPANY_MEMBER_KEY (COMPANY_ID, STATUS);

CREATE TABLE IF NOT EXISTS TB_APPLICATION_COMPANY_JOIN_REQUEST (
    REQUEST_ID BIGINT NOT NULL AUTO_INCREMENT,
    COMPANY_ID BIGINT NOT NULL,
    KEY_ID BIGINT NOT NULL,
    USER_ID BIGINT,
    REQUEST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    MESSAGE VARCHAR(1000),
    REQUESTED_ROLE VARCHAR(30) NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    REQUESTED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    REQUESTED_BY BIGINT,
    DECIDED_AT DATETIME(6),
    DECIDED_BY BIGINT,
    UPDATED_AT DATETIME(6),
    PENDING_USER_ID BIGINT GENERATED ALWAYS AS (
        CASE WHEN STATUS = 'PENDING' THEN USER_ID ELSE NULL END
    ) STORED,
    PRIMARY KEY (REQUEST_ID),
    CONSTRAINT UK_COMPANY_JOIN_REQUEST_PENDING_USER UNIQUE (COMPANY_ID, PENDING_USER_ID),
    CONSTRAINT FK_COMPANY_JOIN_REQUEST_COMPANY
        FOREIGN KEY (COMPANY_ID)
        REFERENCES TB_APPLICATION_COMPANY(COMPANY_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_COMPANY_JOIN_REQUEST_KEY
        FOREIGN KEY (KEY_ID)
        REFERENCES TB_APPLICATION_COMPANY_MEMBER_KEY(KEY_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_COMPANY_JOIN_REQUEST_USER
        FOREIGN KEY (USER_ID)
        REFERENCES TB_APPLICATION_USER(USER_ID)
        ON DELETE SET NULL
);

CREATE INDEX IDX_COMPANY_JOIN_REQUEST_COMPANY_STATUS
    ON TB_APPLICATION_COMPANY_JOIN_REQUEST (COMPANY_ID, STATUS, REQUESTED_AT);

CREATE INDEX IDX_COMPANY_JOIN_REQUEST_USER
    ON TB_APPLICATION_COMPANY_JOIN_REQUEST (USER_ID);
